version: 2

models:

    - name: sales
      description: Teste de primary key na coluna order e product id
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: Teste se tem item vazio em order id
            tests : 
            - not_null 

          - name: products_id
            description: Teste se tem item vazio em  products id
            tests : 
            - not_null 

          - name: qty

          - name: turnover
            description: Teste se tem item vazio em turnover
            tests : 
            - not_null 

          - name: purchase_cost
            tests : 
            - not_null 

          - name: margin